name: Bazel build

on:
  pull_request:

permissions: read-all

jobs:
  bazel-build:
    name: Build and run tests using Bazel
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Clone submodules
        run: git submodule update --init --recursive
      - name: Mount Bazel cache
        uses: actions/cache@v3
        with:
          path: ~/.bazel/cache
          key: bazel-cache-${{ runner.os }}
      - name: Build
        run: bazel --output_user_root=~/.bazel/cache build :all
